# Generated by Django 3.2 on 2021-08-08 10:25

import basic_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название города')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='DisabilityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='группа инвалидности')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'db_table': 'disability_group',
            },
        ),
        migrations.CreateModel(
            name='DysfunctionBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='вид нарушения функций организма')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'db_table': 'dysfunction_body',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='образование')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='тип занятости')),
            ],
            options={
                'db_table': 'employment_type',
            },
        ),
        migrations.CreateModel(
            name='RestrictionCategoriesLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ограничения основных категорий жизнедеятельности')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'db_table': 'restriction_category_life',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='график работы')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название ключевого навыка')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='опыт работы')),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название профессии')),
                ('description', models.TextField(default=basic_data.models.Profession.contact_default, verbose_name='описание профессии')),
                ('boundProfession', models.ManyToManyField(blank=True, related_name='_basic_data_profession_boundProfession_+', to='basic_data.Profession', verbose_name='связанные профессии')),
                ('disabilityGroup', models.ManyToManyField(blank=True, to='basic_data.DisabilityGroup', verbose_name='связанная группа инвалидности')),
                ('dysfunctionBody', models.ManyToManyField(blank=True, to='basic_data.DysfunctionBody', verbose_name='связанный вид нарушения функций организма')),
                ('education', models.ManyToManyField(blank=True, to='basic_data.Education')),
                ('restrictionCategoriesLife', models.ManyToManyField(blank=True, to='basic_data.RestrictionCategoriesLife', verbose_name='связанный ограничения основных категорий жизнедеятельности')),
            ],
            options={
                'db_table': 'profession',
            },
        ),
    ]
