# Generated by Django 3.1.7 on 2021-08-26 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import firm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_user', '0003_auto_20210826_2010'),
        ('basic_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название фирмы')),
                ('description', models.TextField(default=firm.models.Firm.contact_default, verbose_name='описание фирмы')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firm',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=firm.models.WorkPlace.contact_default, max_length=200, verbose_name='Title work place')),
                ('location', models.CharField(default='Державина 15', max_length=200, verbose_name='Адрес')),
                ('min_salary', models.IntegerField(null=True, verbose_name='минимальная зарплата')),
                ('max_salary', models.IntegerField(null=True, verbose_name='максимальная зарплата')),
                ('count', models.IntegerField(default=1, verbose_name='Количество рабочих мест')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата последнего изменения')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='basic_data.city', verbose_name='город')),
                ('disability', models.ManyToManyField(blank=True, to='basic_data.DisabilityGroup', verbose_name='ограничения')),
                ('dysfunctions_body', models.ManyToManyField(blank=True, to='basic_data.DysfunctionBody', verbose_name='физические ограничения')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic_data.education', verbose_name='образование')),
                ('employment_type', models.ManyToManyField(blank=True, to='basic_data.EmploymentType', verbose_name='тип занятости')),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firm.firm', verbose_name='фирма')),
                ('liked_by_profile', models.ManyToManyField(blank=True, related_name='liked_by_profile', to='basic_user.Profile', verbose_name='Пользователи которые лайкнули')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.profession', verbose_name='профессия')),
                ('profile_liked', models.ManyToManyField(blank=True, related_name='profile_liked', to='basic_user.Profile', verbose_name='Пользователи лайкнутые работадателем')),
                ('restrictions_categories_life', models.ManyToManyField(blank=True, to='basic_data.RestrictionCategoriesLife', verbose_name='ограничение категорий жизнедеятельности')),
                ('schedule', models.ManyToManyField(blank=True, to='basic_data.Schedule', verbose_name='график работы')),
                ('skill', models.ManyToManyField(blank=True, to='basic_data.Skill', verbose_name='компетенции')),
            ],
            options={
                'db_table': 'work_place',
            },
        ),
    ]
