# Generated by Django 3.2 on 2021-08-08 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=200, verbose_name='фамилия')),
                ('name2', models.CharField(blank=True, max_length=200, verbose_name='имя')),
                ('name3', models.CharField(blank=True, max_length=200, verbose_name='отчество')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='кортко о себе')),
                ('sex', models.IntegerField(blank=True, default=1, verbose_name='пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_profile',
            },
        ),
    ]
