# Generated by Django 3.2 on 2021-08-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
